version: '3'
services:
  client:
    build:
      context: C:\\Users\\User\\Documents\\Projects\\Devang\\oce007\\view
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - mern-network
    volumes:
      - C:\\Users\\User\\Documents\\Projects\\Devang\\oce007\\view\\src
      - C:\\Users\\User\\Documents\\Projects\\Devang\\oce007\\view\\public
    depends_on:
      - server
    environment:
      - REACT_APP_SERVER=http://localhost:5000
      - CHOKIDAR_USEPOLLING=true
    command: yarn start
    stdin_open: true
    tty: true

  server:
    build:
      context: C:\\Users\\User\\Documents\\Projects\\Devang\\oce007
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    networks:
      - mern-network
    volumes:
      - C:\\Users\\User\\Documents\\Projects\\Devang\\oce007
    environment:
      - CLIENT=http://localhost:3000
    command: nodemon -L C:\\Users\\User\\Documents\\Projects\\Devang\\oce007\\oce.server.js

networks:
  mern-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
